### PR TITLE
new request filter monitors incoming request parameters

### PR DESCRIPTION
**Pull request by pguhl**
for logged in user, whenever locale parameter specified, the filter will attempt to translate the input into locale and store in the user preferences

### CODE REVIEW

**Comment by jekutzsche** [comment]
What do you think about the alternative implementation with Spring classes in the following commit?
https://github.com/quarano/quarano-application/pull/123/commits/37b08aa011b7c87c11cf708eb9419a9a6cd90339

**Comment by pguhl** [comment]
The interceptor variation implemented by Jens means less code and we don't need duplicates.

**Comment by pguhl** [comment]
> @pguhl what do you think about the alternative implementation with Spring classes in the following commit?
> [37b08aa](https://github.com/quarano/quarano-application/commit/37b08aa011b7c87c11cf708eb9419a9a6cd90339)

Yes, let's stick to your alternative as it means less code on our side. But what if we move the check here for supported languages to this interceptor, to the write operation? We read way more often then write.

**Comment by jekutzsche** [comment]
Then it does not match the requirement in the ticket!

"Wenn festgestellt wird, dass die vom frontend geschickte sprache nicht im Backend unterstützt wird, wird diese dennoch gespeichert, aber Serverantworten werden im Fallback deutsch geschickt"

**Comment by pguhl** [comment]
Good! Agreed

**Pull request closed without merging**
